"""add indexes for performance

Revision ID: b3207f9705b2
Revises: 998e2824efc2
Create Date: 2026-06-12 17:16:02.879765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3207f9705b2'
down_revision = '998e2824efc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_task_user_deleted', ['user_id', 'is_deleted'], unique=False)
        batch_op.create_index('ix_task_user_status_due', ['user_id', 'status', 'due_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_task_user_status_due')
        batch_op.drop_index('ix_task_user_deleted')

    # ### end Alembic commands ###
